# Generated by Django 4.1.3 on 2023-03-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
