# Generated by Django 4.1.3 on 2023-04-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='disc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='mrp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='sale_price',
            field=models.FloatField(default=0),
        ),
    ]
