# Generated by Django 4.1.3 on 2023-04-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_disc_products_mrp_products_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Kurtis', 'Kurtis'), ('Leggings', 'Leggings'), ('Pants', 'Pants')], default='Kurtis', max_length=20),
        ),
    ]
