# Generated by Django 4.1.3 on 2023-04-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sizes',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
