# Generated by Django 4.1.3 on 2023-04-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='feature',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
